apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sandwichclound.api.fullname" . }}
  labels:
    app: {{ template "sandwichclound.name" . }}
    component: {{ .Values.api.name }}
    chart: {{ template "sandwichclound.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  # Github Auth
  githubClientID: {{ .Values.api.auth.github.clientID | b64enc | quote }}
  githubClientSecret: {{ .Values.api.auth.github.clientSecret | b64enc | quote }}
  # Database Auth
  databasePassword: {{ .Values.api.auth.database.password | b64enc | quote }}
