{{- if .Values.api.ingress.enabled -}}
{{- $fullName := include "sandwichclound.api.fullname" . -}}
{{- $servicePort := .Values.api.service.port -}}
{{- $ingressPath := .Values.api.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "sandwichclound.name" . }}
    component: {{ .Values.api.name }}
    chart: {{ template "sandwichclound.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
{{- if .Values.api.ingress.tls }}
  tls:
  {{- range .Values.api.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.api.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
  {{- end }}
{{- end }}
