apiVersion: v1
kind: Service
metadata:
  name: {{ template "sandwichclound.api.fullname" . }}
  labels:
    app: {{ template "sandwichclound.name" . }}
    component: {{ .Values.api.name }}
    chart: {{ template "sandwichclound.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ template "sandwichclound.name" . }}
    component: {{ .Values.api.name }}
    release: {{ .Release.Name }}
