apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sandwichclound.fullname" . }}-common
  labels:
    app: {{ template "sandwichclound.name" . }}
    component: common
    chart: {{ template "sandwichclound.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  fernetKey: {{ index .Values.common.auth.fernetKeys 0 | b64enc | quote }}
  fernetKeys: {{ .Values.common.auth.fernetKeys | join "," | b64enc | quote }}
