apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sandwichclound.manager.fullname" . }}
  labels:
    app: {{ template "sandwichclound.name" . }}
    component: {{ .Values.manager.name }}
    chart: {{ template "sandwichclound.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  vcenterPassword: {{ .Values.manager.vcenter.password | b64enc | quote }}
