{{- if .Values.common.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.common.rbac.serviceAccount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sandwich
rules:
- nonResourceURLs:
  - /version
  - /version/
  verbs:
    - get
- apiGroups:
  - ""
  resources:
  - namespaces
  - endpoints
  verbs:
  - '*'
- apiGroups:
  - sandwichcloud.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - get
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sandwich:clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sandwich
subjects:
- kind: ServiceAccount
  name: {{ .Values.common.rbac.serviceAccount }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
